### ISSUE TITLE
Add to official (and unofficial) TOML lists

### ISSUE THREAD

**Issue by epage** [ota-meshi/toml-eslint-parser#156]
I found out about this parser because it was used to close renovatebot/renovate#18668.

It isn't listed:
- [As an official implementation](https://github.com/toml-lang/toml/wiki) (though it is among the Validators and Formatter lists)
- Among the [unofficial conformance / performance matrix](https://arp242.github.io/toml-test-matrix/)

**Comment by ota-meshi** [comment]
Thanks for the suggestion!
This parser is different from other parsers as its main purpose is to generate an AST. So I think people get confused when this parser is in the same list. What do you think? Do you think it should be added to the list?

**Comment by epage** [comment]
If this is fully conformant, than I think it'd be worth it since there isn't one for JS (at least on the matrix page).  The downside would be the potential for an influx of users making requests for regular TOML parsing needs and I can see that be a reason to not advertise it.

For context, I maintain a TOML parser for Rust and it has two levels to its API, the `toml` package for high level operations and `toml_edit` for format-preserving edits.  I have both on there.

**Comment by ota-meshi** [comment]
Thank you for your opinion!
I've added it to the official list.
This parser does not have a serializer, so I would like to consider later how to add it to the performance matrix. Therefore, I will leave this issue open.

**Comment by epage** [comment]
> This parser does not have a serializer, so I would like to consider later how to add it to the performance matrix. Therefore, I will leave this issue open.

There are other implementations without the encoder validation on the matrix, like Python's `tomllib`.
