### ISSUE TITLE
parser and AST as a separated library?

### ISSUE THREAD

**Issue by anatawa12** [ota-meshi/toml-eslint-parser#72]
I want a library that implements AST for TOML for node.js. this eslint plugin looks to have that mechanism but is not a simple library. Could you publish it as a separate library?

**Comment by anatawa12** [comment]
Sorry, i found the AST tree doesn't have full information about TOML file like whitespace so this is not what i want.

**Comment by trim21** [comment]
do you have a solution for it？

**Comment by anatawa12** [comment]
No, I temporary used regex for (loose) matching, and after that for other reasons my use case is completely rewritten with rust.
